const CONTEXT_MENU_ON = 'CONTEXT_MENU_ON';
const CONTEXT_MENU_OFF = 'CONTEXT_MENU_OFF';
const SET_CONTEXT_MENU_ON = 'SET_CONTEXT_MENU_ON';
const SET_CONTEXT_MENU_OFF = 'SET_CONTEXT_MENU_OFF';

// context payload types
const CONTEXT_SONG = 'CONTEXT_SONG';
const CONTEXT_ALBUM = 'CONTEXT_ALBUM';
const CONTEXT_ARTIST = 'CONTEXT_ARTIST';
const CONTEXT_PLAYLIST = 'CONTEXT_PLAYLIST';
const CONTEXT_UPLAYLIST = 'CONTEXT_UPLAYLIST';

module.exports = {
  CONTEXT_MENU_ON,
  CONTEXT_MENU_OFF,
  SET_CONTEXT_MENU_ON,
  SET_CONTEXT_MENU_OFF,

  CONTEXT_SONG,
  CONTEXT_ALBUM,
  CONTEXT_ARTIST,
  CONTEXT_PLAYLIST,
  CONTEXT_UPLAYLIST,
};
