const CONTEXT_MENU_ON = 'CONTEXT_MENU_ON';
const CONTEXT_MENU_OFF = 'CONTEXT_MENU_OFF';
const CONTEXT_MENU_ON_REQUEST = 'CONTEXT_MENU_ON_REQUEST';
const CONTEXT_MENU_OFF_REQUEST = 'CONTEXT_MENU_OFF_REQUEST';

// context payload types
const CONTEXT_TRACK = 'CONTEXT_TRACK';
const CONTEXT_ALBUM = 'CONTEXT_ALBUM';
const CONTEXT_ARTIST = 'CONTEXT_ARTIST';
const CONTEXT_PLAYLIST = 'CONTEXT_PLAYLIST';
const CONTEXT_UPLAYLIST = 'CONTEXT_UPLAYLIST';

module.exports = {
  CONTEXT_MENU_ON,
  CONTEXT_MENU_OFF,
  CONTEXT_MENU_ON_REQUEST,
  CONTEXT_MENU_OFF_REQUEST,

  CONTEXT_TRACK,
  CONTEXT_ALBUM,
  CONTEXT_ARTIST,
  CONTEXT_PLAYLIST,
  CONTEXT_UPLAYLIST,
};
