const CONTEXT_MENU_ON = 'CONTEXT_MENU_ON';
const CONTEXT_MENU_OFF = 'CONTEXT_MENU_OFF';
const SET_CONTEXT_MENU_ON = 'SET_CONTEXT_MENU_ON';
const SET_CONTEXT_MENU_OFF = 'SET_CONTEXT_MENU_OFF';

module.exports = {
  CONTEXT_MENU_ON,
  CONTEXT_MENU_OFF,
  SET_CONTEXT_MENU_ON,
  SET_CONTEXT_MENU_OFF,
};
