const NOTIFICATION = 'NOTIFICATION';
const NOTIFICATION_DURATION = 8000; // delay before closing the notification [in milliseconds]
const NOTIFICATION_ON_REQUEST = 'NOTIFICATION_ON_REQUEST';
const NOTIFICATION_OFF_REQUEST = 'NOTIFICATION_OFF_REQUEST';

module.exports = {
  NOTIFICATION,
  NOTIFICATION_DURATION,
  NOTIFICATION_ON_REQUEST,
  NOTIFICATION_OFF_REQUEST,
};
