const QUEUE_SET = 'QUEUE_SET';
const QUEUE_ADD = 'QUEUE_ADD';
const QUEUE_REMOVE = 'QUEUE_REMOVE';
const QUEUE_CLEAR = 'QUEUE_CLEAR';
const SET_QUEUE_SET = 'SET_QUEUE_SET';
const SET_QUEUE_ADD = 'SET_QUEUE_ADD';
const SET_QUEUE_REMOVE = 'SET_QUEUE_REMOVE';
const SET_QUEUE_CLEAR = 'SET_QUEUE_CLEAR';

module.exports = {
  QUEUE_SET,
  QUEUE_ADD,
  QUEUE_REMOVE,
  QUEUE_CLEAR,
  SET_QUEUE_SET,
  SET_QUEUE_ADD,
  SET_QUEUE_REMOVE,
  SET_QUEUE_CLEAR,
};
