const QUEUE_SET = 'QUEUE_SET';
const QUEUE_ADD = 'QUEUE_ADD';
const QUEUE_REMOVE = 'QUEUE_REMOVE';
const QUEUE_CLEAR = 'QUEUE_CLEAR';
const QUEUE_SET_REQUEST = 'QUEUE_SET_REQUEST';
const QUEUE_ADD_REQUEST = 'QUEUE_ADD_REQUEST';
const QUEUE_REMOVE_REQUEST = 'QUEUE_REMOVE_REQUEST';
const QUEUE_CLEAR_REQUEST = 'QUEUE_CLEAR_REQUEST';

module.exports = {
  QUEUE_SET,
  QUEUE_ADD,
  QUEUE_REMOVE,
  QUEUE_CLEAR,
  QUEUE_SET_REQUEST,
  QUEUE_ADD_REQUEST,
  QUEUE_REMOVE_REQUEST,
  QUEUE_CLEAR_REQUEST,
};
