const PLAY = 'PLAY';
const NEXT = 'NEXT';
const PREVIOUS = 'PREVIOUS';
const SEEK = 'SEEK';
const TOGGLE_PLAY_PAUSE = 'TOGGLE_PLAY_PAUSE';
const PREVIOUS_THRESHOLD = 2;

module.exports = {
  PLAY,
  NEXT,
  PREVIOUS,
  SEEK,
  TOGGLE_PLAY_PAUSE,
  PREVIOUS_THRESHOLD,
};
