const PLAY_REQUEST = 'PLAY_REQUEST';
const NEXT_REQUEST = 'NEXT_REQUEST';
const PREVIOUS_REQUEST = 'PREVIOUS_REQUEST';
const SEEK_REQUEST = 'SEEK_REQUEST';
const PLAY_PAUSE_REQUEST = 'PLAY_PAUSE_REQUEST';
const PREVIOUS_THRESHOLD = 2;

module.exports = {
  PLAY_REQUEST,
  NEXT_REQUEST,
  PREVIOUS_REQUEST,
  SEEK_REQUEST,
  PLAY_PAUSE_REQUEST,
  PREVIOUS_THRESHOLD,
};
