export const PLAY_REQUEST = 'PLAY_REQUEST';
export const NEXT_REQUEST = 'NEXT_REQUEST';
export const PREVIOUS_REQUEST = 'PREVIOUS_REQUEST';
export const SEEK_REQUEST = 'SEEK_REQUEST';
export const PLAY_PAUSE_REQUEST = 'PLAY_PAUSE_REQUEST';
export const PREVIOUS_THRESHOLD = 2;
